#!/usr/bin/env bash
# Install the `lathe` template into the llm utility's template directory.
#
#   ./llm-template/install.sh          # install / reinstall
#
# The template is three absolute paths. Nothing is copied, so the SKILL.md the
# template feeds the model is the same file the coding agents read -- it cannot
# drift from the source of truth the way a pasted copy would.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/.." && pwd)"

# Prefer the installed skill (what `lathe skills install` wrote, and what the
# coding agents actually load); fall back to this checkout's copy.
skill="$HOME/.claude/skills/lathe/SKILL.md"
[ -f "$skill" ] || skill="$repo/.claude/skills/lathe/SKILL.md"
[ -f "$skill" ] || { echo "no lathe SKILL.md found (tried ~/.claude/skills and $repo/.claude/skills)" >&2; exit 1; }

command -v llm >/dev/null || { echo "llm is not on PATH" >&2; exit 1; }
dir="$(llm templates path)"
mkdir -p "$dir"

# The goal is that bare `llm -t lathe '<topic>'` works, so the template pins a
# model rather than falling through to llm's default (which needs an OpenAI key
# this machine does not have). `-m <model>` on the command line still wins, and
# whatever wins is what gets recorded in the tutorial's metadata -- see
# `_resolved_model()` in tools.py.
model="${LATHE_LLM_MODEL:-sonnet-4.6}"

cat > "$dir/lathe.yaml" <<YAML
name: lathe
model: $model
system_fragments:
- $skill
- $here/adapter.md
- $here/adapter-oneshot.md
functions: $here/tools.py
YAML

# `llm chat` reads a template's `model` and `functions` but never its
# `system_fragments` -- verified against llm 0.33's cli.py, where the chat
# command touches only those two fields and `_apply_template` handles `system`
# alone. A chat started with `-t lathe` therefore gets the tools and no skill,
# with no warning. This wrapper passes the fragments explicitly instead, swaps
# the one-shot turn budget for the chat fragment, and lifts the chain limit.
cat > "$here/lathe-chat" <<SH
#!/usr/bin/env bash
# Interactive /lathe. Generated by install.sh -- edit that, not this.
set -euo pipefail
exec llm chat -t lathe --cl 0 \\
  --sf "$skill" \\
  --sf "$here/adapter.md" \\
  --sf "$here/adapter-chat.md" "\$@"
SH
chmod +x "$here/lathe-chat"

if [ -d "$HOME/.local/bin" ]; then
  ln -sf "$here/lathe-chat" "$HOME/.local/bin/lathe-chat"
  linked="$HOME/.local/bin/lathe-chat"
else
  linked="(no ~/.local/bin; run $here/lathe-chat directly)"
fi

echo "installed $dir/lathe.yaml"
echo "  model:    $model  (override: LATHE_LLM_MODEL=... ./install.sh, or llm -m ...)"
echo "  skill:    $skill"
echo "  adapter:  $here/adapter.md"
echo "  tools:    $here/tools.py"
echo
echo "  chat:     $here/lathe-chat -> $linked"
echo
echo "usage: llm -t lathe 'build a digital synth in Zig'   # one-shot"
echo "       lathe-chat                                     # interactive"
